### ISSUE TITLE
not compatible with PE2018

### ISSUE THREAD

**Issue by vchepkov** [tkishel/pe_tune#2]
Fails with PE2018:

```
/opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- puppet/util/pe_conf (LoadError)
	from /opt/puppetlabs/puppet/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /root/pe_tune/lib/puppet_x/puppetlabs/tune/configuration.rb:2:in `<top (required)>'
	from ./pe_tune/lib/puppet_x/puppetlabs/tune.rb:475:in `require_relative'
	from ./pe_tune/lib/puppet_x/puppetlabs/tune.rb:475:in `<main>'

```

**Comment by csabo** [comment]
Can confirm, having the same issue.

**Comment by tkishel** [comment]
Thanks. 

I've just tested and pushed a commit to address this. Please download a new version, and review the Setup and Usage sections in the README, as both have changed. If you continue to receive an error, please run the script with `--debug` and verify that it is loading the enterprise modules.

**Comment by vchepkov** [comment]
Beginning of the end of github, sigh

```
# git pull
fatal: unable to access 'https://github.com/tkishel/pe_tune.git/': Encountered end of file
```

**Comment by vchepkov** [comment]
It works now, Tom, thank you.

**Comment by tkishel** [comment]
Thanks for filing this!
